services:
  app:
    container_name: ai
    build: .
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PERSONAL_API_KEY: "${PERSONAL_API_KEY}"

networks:
  default:
    name: webproxy
    external: true
